import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e2e2e2",
        "on-primary-fixed-variant": "#005047",
        "on-secondary": "#620040",
        "primary-fixed": "#62fae3",
        "on-primary-container": "#00423b",
        "tertiary-fixed": "#ffdf9f",
        "surface-container-low": "#1b1b1b",
        "surface-dim": "#131313",
        "on-surface-variant": "#bbcac6",
        "surface-container": "#1f1f1f",
        "on-primary-fixed": "#00201c",
        "secondary-fixed": "#ffd8e7",
        "on-secondary-fixed": "#3d0026",
        "surface-container-highest": "#353535",
        "on-tertiary": "#402d00",
        "secondary-container": "#85145a",
        "on-error": "#690005",
        secondary: "#ffafd3",
        "on-tertiary-fixed": "#261a00",
        "on-tertiary-fixed-variant": "#5c4300",
        "outline-variant": "#3c4947",
        "on-background": "#e2e2e2",
        "surface-container-high": "#2a2a2a",
        "inverse-primary": "#006b5f",
        background: "#131313",
        "tertiary-container": "#d09c00",
        "surface-bright": "#393939",
        primary: "#3cddc7",
        "surface-variant": "#353535",
        "primary-fixed-dim": "#3cddc7",
        "on-primary": "#003731",
        error: "#ffb4ab",
        "surface-tint": "#3cddc7",
        "on-tertiary-container": "#4c3700",
        "inverse-on-surface": "#303030",
        "secondary-fixed-dim": "#ffafd3",
        "on-secondary-fixed-variant": "#85145a",
        "tertiary-fixed-dim": "#f9bd22",
        surface: "#131313",
        "on-surface": "#e2e2e2",
        "error-container": "#93000a",
        outline: "#859490",
        tertiary: "#f9bd22",
        "on-error-container": "#ffdad6",
        "primary-container": "#00b8a5",
        "on-secondary-container": "#ff93c8",
        "surface-container-lowest": "#0e0e0e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
